export const SINGAPORE_DISTRICTS = [
  "All Districts",
  "Ang Mo Kio",
  "Bedok",
  "Bishan",
  "Bukit Batok",
  "Bukit Merah",
  "Bukit Timah",
  "CBD / Raffles Place",
  "Changi",
  "Chinatown",
  "Clementi",
  "Geylang",
  "Hougang",
  "Jurong East",
  "Jurong West",
  "Kallang",
  "Marina Bay",
  "Novena",
  "Orchard",
  "Pasir Ris",
  "Punggol",
  "Queenstown",
  "Sembawang",
  "Sengkang",
  "Serangoon",
  "Tampines",
  "Toa Payoh",
  "Woodlands",
  "Yishun",
] as const;

export const BUSINESS_CATEGORIES = [
  "All Categories",
  "Food & Beverage",
  "Retail & Shopping",
  "Healthcare & Medical",
  "Education & Training",
  "Professional Services",
  "Beauty & Wellness",
  "Home Services",
  "Automotive",
  "Technology & IT",
  "Real Estate",
  "Legal Services",
  "Financial Services",
  "Logistics & Transport",
  "Events & Entertainment",
  "Construction & Renovation",
] as const;
